[package]
name = "giftwrap_launcher"
version = "0.1.0"
authors = ["Bradley Bridges <bradley@bbridges.io>"]
edition = "2018"

[[bin]]
name = "launcher"
path = "src/main.rs"

[dependencies]
giftwrap_archive = { path = "../giftwrap_archive", version = "0.1.0" }
