[package]
name = "launcher"
version = "0.1.0"
authors = ["Bradley Bridges <bradley@bbridges.io>"]
edition = "2018"

[dependencies]
errno = "0.2.7"
libc = "0.2.86"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4.32"
