name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lib:
    name: Build Libraries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12'

      - name: Build lib/giftwrap
        run: rebar3 build
        working-directory: lib/giftwrap

      - name: Build lib/rebar3_giftwrap
        run: rebar3 build
        working-directory: lib/rebar3_giftwrap

      - name: Build lib/mix_giftwrap
        run: |
          mix deps.get
          mix compile
        working-directory: lib/mix_giftwrap
      - name: Test lib/mix_giftwrap
        run: mix test
        working-directory: lib/mix_giftwrap

      - name: Check lib/mix_giftwrap code formatting
        run: mix format --check-formatted
        working-directory: lib/mix_giftwrap

  build_launcher:
    name: Build Launcher
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Build launcher
        run: cargo build --all-features
        working-directory: launcher

      - name: Check launcher code formatting   
        run: cargo format --all -- --check
        working-directory: launcher
      - name: Check launcher clippy warnings
        run: cargo clippy --all-features -- -D warnings
        working-directory: launcher
